import os
from pathlib import Path


SPEECH_UTILS_DB_ROOT_DIR = Path(os.environ.get("SPEECH_UTILS_DB_ROOT_DIR"))
SPEECH_UTILS_DB_METADATA_PATH = SPEECH_UTILS_DB_ROOT_DIR / "metadata.duckdb"
SPEECH_UTILS_DB_UTTERANCES_TABLE_NAME = "utterances"
SPEECH_UTILS_DB_NOISES_TABLE_NAME = "noises"
SPEECH_UTILS_DB_NOISE_CONFIGS_TABLE_NAME = "noise_configs"

SPEECH_UTILS_CORPORA_ROOT_DIR = Path(os.environ.get("SPEECH_UTILS_CORPORA_ROOT_DIR"))
SPEECH_UTILS_CORPORA_LIBRISPEECH_DIR = SPEECH_UTILS_CORPORA_ROOT_DIR / "LibriSpeech"
SPEECH_UTILS_CORPORA_LIBRITTS_DIR = SPEECH_UTILS_CORPORA_ROOT_DIR / "LibriTTS"
SPEECH_UTILS_CORPORA_VCTK_DIR = SPEECH_UTILS_CORPORA_ROOT_DIR / "VCTK"
SPEECH_UTILS_CORPORA_DEMAND_DIR = SPEECH_UTILS_CORPORA_ROOT_DIR / "DEMAND"
